### ISSUE TITLE
VERIFICAR Y AGREGAR UNA CONFIRMACIÓN DE UN NOMBRE PARA TU TRIBIA

### ISSUE THREAD

**Issue by VictorMaJa** [eliaschampi/Trivia-PiedraPapeTijera#1]
Como se puede observar en la siguiente pregunta: Me podrías decir como quieres que te llame?
Aparece vacío cuando no se ingresa ningún nombre
![issues elias](https://user-images.githubusercontent.com/113326698/190547931-d35c3655-0aba-49a9-b61a-1b7b614a2c10.png)

Cuando se escribe números también se confirma, solo se debe ingresar nombres de personas o solo letras, es sugerencia !
![issues elias 2](https://user-images.githubusercontent.com/113326698/190548332-38fee2f6-cde7-4c69-bffb-9e60b0e34be4.png)

Agregar en la línea 163 del código la validación para el nombre o asignar  un nombre para la trivia piedra, papel o tijera.
![issues elias 3](https://user-images.githubusercontent.com/113326698/190548860-81ba712b-999b-488c-b2d8-d303fcc5c58f.png)

Saludos

**Comment by VictorMaJa** [comment]
### REVISAR LOS INTENTOS PERMITIDOS EN EL MENU DEL JUEGO CUANDO SE QUIERE INGRESAR UNA OPCIÓN PARA JUGAR 
![issues elias 4](https://user-images.githubusercontent.com/113326698/190552934-786e2df3-acde-40db-bd29-b76b5e1505b1.png)

Puede ingresar en esta línea de código los intentos permitidos para que no ocurra error; también sucede en la opción configurar premio
![issues elias 5](https://user-images.githubusercontent.com/113326698/190552956-a6208a5e-5d44-478d-97a1-ae67c02c3016.png)

**Comment by eliaschampi** [comment]
**Hola victor, muchisimas gracias por tu observacion, efectivamente era un error que permitia que mi codigo permitiera ingresar campo vacio como nombre**

_Ya he corregido el siguiente commit_

https://github.com/eliaschampi/Trivia-PiedraPapeTijera/commit/e1f102eb20f4fe59218a71da40390a565531361f

Como se puede observar, el campo nombre ya es obligatorio.
![imagen](https://user-images.githubusercontent.com/26263355/190886163-fe9a0204-43f0-43a4-a1de-a85916503df0.png)


Saludos
