### ISSUE TITLE
REVISAR LOS INTENTOS PERMITIDOS EN EL MENU DEL JUEGO CUANDO SE QUIERE INGRESAR UNA OPCIÓN PARA JUGAR

### ISSUE THREAD

**Issue by VictorMaJa** [eliaschampi/Trivia-PiedraPapeTijera#3]
![issues elias 4](https://user-images.githubusercontent.com/113326698/190836094-2d757d5e-2e13-43a6-97cd-8abe44c4cb98.png)

Puede ingresar en esta línea de código los intentos permitidos para que no aparezca el error; también sucede en la opción configurar premio

![issues elias 5](https://user-images.githubusercontent.com/113326698/190836108-214453f7-5ef3-439c-ab09-994e37772dc8.png)

**Comment by eliaschampi** [comment]
### **Hey, Victor un gran saludo y agradezco tu observación**
**Efectivamente el usuario al ingresar una opcion podia intentar tantas veces fuera necesario, lo cual no era logicamente correcto, deberia haber un limite**

_Por ello en el siguiente commit he solucionado  para que el usuario solo disponga de tres intentos si ingresa otra alternativa no establecida o campo vacio_

https://github.com/eliaschampi/Trivia-PiedraPapeTijera/commit/e1f102eb20f4fe59218a71da40390a565531361f

Como solución el juego se cierra si el usuario intento mas de tres veces.

¿Alguna sugerencia?

Muchas gracias y quedo atento a tus observaciones
