### ISSUE TITLE
AÑADIR UN MENSAJE DE DESPEDIDA FINAL PARA TU TRIVIA CUANDO SE TERMINA DE JUGAR!

### ISSUE THREAD

**Issue by VictorMaJa** [eliaschampi/Trivia-PiedraPapeTijera#4]
Hola que tal me gusta tu trivia es un juego muy divertido, jugar con la maquina y ganarle es estupendo. Puedes agregar un mensaje final como despedida como agradeciendo a los que juegan la trivia piedra, papel o tijera en la opción SALIR DEL JUEGO
Por lo demás esta estupendo tu trivia. Saludos Elías

**Por ejemplo asi:**
![mensaje despedida](https://user-images.githubusercontent.com/113326698/190942664-b79482fd-710d-49cf-bc05-a1fe9c780c67.png)

**Comment by eliaschampi** [comment]
**Buenas noches Victor, ya se ha agregado el mensaje de despedida**
Este es el commit con ese cambio👇
https://github.com/eliaschampi/Trivia-PiedraPapeTijera/commit/e749bf36783d8344c0609f565cff8eb960418a19

Muchas gracias y saludos cordiales 👍🙂
